# Generated by Django 5.0.4 on 2024-05-02 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='date',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='description',
        ),
        migrations.AddField(
            model_name='podcast',
            name='artist_image',
            field=models.ImageField(default='media/default/default.webp', upload_to='podcasts/artists/'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='podcast',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
