# Generated by Django 5.0.4 on 2024-05-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_podcast_poster_alter_podcast_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
