# Generated by Django 5.0.4 on 2024-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_liveshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveshow',
            name='image',
            field=models.ImageField(upload_to='live_shows/'),
        ),
        migrations.AlterField(
            model_name='liveshow',
            name='live_status',
            field=models.BooleanField(default=False),
        ),
    ]
