# Generated by Django 5.0.4 on 2024-05-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_radiosettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liveshow',
            name='audio_stream_url',
        ),
        migrations.RemoveField(
            model_name='radiosettings',
            name='stream_url',
        ),
    ]
