# Generated by Django 5.0.4 on 2024-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_remove_liveshow_audio_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosettings',
            name='stream_url',
            field=models.URLField(default='https://ritmolatinoscs.radioca.st/stream?type=http&amp%3Bnocache=7469', editable=False),
        ),
    ]
