# Generated by Django 5.0.4 on 2024-05-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0011_liveshow_radiosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiosettings',
            name='live_show_title',
            field=models.CharField(default='Default Live Show Title', max_length=100),
        ),
    ]
