# Generated by Django 5.0.4 on 2024-05-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0012_radiosettings_live_show_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiosettings',
            name='live_show_title',
        ),
    ]
