# Generated by Django 5.0.4 on 2024-05-03 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0014_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
