# Generated by Django 5.0.4 on 2024-05-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_blogpost_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
