# Generated by Django 5.0.4 on 2024-05-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0019_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveshow',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
    ]
