# Generated by Django 5.0.4 on 2024-05-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0022_category_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
