# Generated by Django 5.0.4 on 2024-05-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0027_radiojockey_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RadioJockey',
            new_name='DJ',
        ),
    ]
