# Generated by Django 5.0.4 on 2024-05-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0028_rename_radiojockey_dj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='image',
            field=models.ImageField(upload_to='dj_photos/'),
        ),
    ]
