# Generated by Django 5.0.4 on 2024-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0029_alter_dj_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='facebook_url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dj',
            name='instagram_url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dj',
            name='linkedin_url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='dj',
            name='twitter_url',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
