# Generated by Django 5.1 on 2024-08-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0030_dj_facebook_url_dj_instagram_url_dj_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0),
        ),
    ]
